version: "3.8"

services:
  app:
    container_name: app_gin
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile # Dockerfile のあるディレクトリを相対パスで指定
    tty: true # コンテナが落ちないようにする
    volumes:
      - ./app:/app # ホストのディレクトリ:コンテナのディレクトリ
    #environment:
    #- HOGE=hoge
    #env_file:
    #  - ./.env
    ports:
      - "5003:8000" # ホストのポート:コンテナのポート
